meta-xilinx-mali400: mask graphic recipes when mali400 is not enabled
Issue: LIN1024-3226

There is a type of definition in many recipes in meta-xilinx-mali400:

    PACKAGE_ARCH_DEFAULT := "${PACKAGE_ARCH}"
    PACKAGE_ARCH = "${@bb.utils.contains('MACHINE_FEATURES', 'mali400', '${MALI_PACKAGE_ARCH}', '${PACKAGE_ARCH_DEFAULT}', d)}"

When multilib image is built, PACKAGE_ARCH for packages which should
be "armv7at2hf-neon", but after the above operations, PACKAGE_ARCH
of this packages has been changed as "cortexa53", this triggers the
multilib building error:

    ERROR: The sstate manifest for task 'lib32-mesa:populate_sysroot' (multilib variant 'lib32') could not be found.
    The pkgarchs considered were: amd_zynqmp, armv7at2hf-neon, armv7ahf-neon, armv7at2hf-vfp, armv7ahf-vfp, armv6thf-vfp, armv6hf-vfp, armv5tehf-vfp, armv5ehf-vfp, armv5thf-vfp, armv5hf-vfp, allarch, x86_64_x86_64-nativesdk.

Let's mask these recipes when mali400 is not enabled.

(LOCAL REV: NOT UPSTREAM) - WRLinux Specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>