meta-xilinx-core: install boot.scr file only without ostree
Issue: LINUXEXEC-33555

Both u-boot-xlnx-scr.bb in meta-xilinx and u-boot-uenv.bb in
wrlinux layer install /boot/boot.scr to their packages and this will
trigger the error:

    Error: Transaction test error:
	file /boot/boot.scr conflicts between attempted installs of u-boot-uenv-2.0-r0.amd_zynqmp and u-boot-xlnx-scr-1.0-r0.amd_zynqmp

Add a condition check in u-boot-xlnx-scr.bb to fix this issue.

(LOCAL REV: NOT UPSTREAM) - WRLinux Specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>