meta-xilinx-mali400: fix argument issue for of_property_for_each_u32
Issue: LIN1024-10257

This commit is to fix the compile error:

tmp-glibc/work/amd_zynqmp-wrs-linux/kernel-module-mali/r9p0-01rel0/DX910-SW-99002-r9p0-01rel0/driver/src/devicedrv/mali/linux/mali_osk_mali.c:241:9: note: each undeclared identifier is reported only once for each function it appears in
TOPDIR/tmp-glibc/work/amd_zynqmp-wrs-linux/kernel-module-mali/r9p0-01rel0/DX910-SW-99002-r9p0-01rel0/driver/src/devicedrv/mali/linux/mali_osk_mali.c:241:33: error: expected ';' before '{' token
  241 |         of_property_for_each_u32(node, "pmu_domain_config", prop, p, u) {
      |                                 ^                                       ~

Since Xilinx SDK kernel is staying at a fix commit, this modification is
only for WRLinux.

And due to the rebase of this layer, the patch
"0030-fix-argument-issue-for-of_property_for_each_u32.patch" is
invalid, and I make a new patch to replace it.

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>